services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - "/:/host"
  app:
    image: nginx:alpine
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "80:80"
